apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/
  - minio/
  - loki/
  - promtail/
  - prometheus/
  - kube-state-metrics/
  - node-exporter/
  - grafana/
  - mysql-exporter/
  - mssql-exporter/
  - redis-exporter/
