apiVersion: v1
kind: Pod
metadata:
  name: grafana
  namespace: logging
  labels:
    app: grafana
spec:
  containers:
  - name: grafana
    image: grafana/grafana-oss:latest
    ports:
    - containerPort: 3000
    resources:
      limits:
        memory: "150Mi"
      requests:
        memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: logging
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32123
