apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: logging
  labels:
    app: grafana
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus.logging.svc.cluster.local:9090
        isDefault: false
        editable: false
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki.logging.svc.cluster.local:3100
        isDefault: false
        editable: false
