apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
      - name: grafana
        image: grafana/grafana:latest
        env:
        - name: GF_SERVER_ROOT_URL
          value: https://log.pirago.work
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
          value: /etc/grafana/provisioning/dashboards/json/monitoring-overview.json
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: logging-secrets
              key: GRAFANA_ADMIN_PASSWORD
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
          readOnly: true
        - name: dashboards-provider
          mountPath: /etc/grafana/provisioning/dashboards
          readOnly: true
        - name: dashboards-json
          mountPath: /etc/grafana/provisioning/dashboards/json
          readOnly: true
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: datasources
        configMap:
          name: grafana-datasources
      - name: dashboards-provider
        configMap:
          name: grafana-dashboards-provider
      - name: dashboards-json
        configMap:
          name: grafana-dashboards-json
