apiVersion: v1
kind: Service
metadata:
  name: mssql-exporter
  namespace: logging
  labels:
    app: mssql-exporter
spec:
  selector:
    app: mssql-exporter
  ports:
    - port: 4000
      targetPort: 4000
      name: metrics
