apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: logging
  labels:
    app: redis-exporter
spec:
  selector:
    app: redis-exporter
  ports:
    - port: 9121
      targetPort: 9121
      name: metrics
