apiVersion: v1
kind: Secret
metadata:
  name: logging-secrets
  namespace: logging
type: Opaque
stringData:
  GRAFANA_ADMIN_PASSWORD: "<YOUR_GRAFANA_PASSWORD>"
  MINIO_ROOT_PASSWORD: "<YOUR_MINIO_PASSWORD>"
