apiVersion: v1
kind: Pod
metadata:
  name: minio
  namespace: storage
  labels:
    app: minio
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    args:
    - server
    - /data
    - --console-address
    - ":9001"
    env:
    - name: MINIO_ROOT_USER
      value: adminadmin
    - name: MINIO_ROOT_PASSWORD
      value: adminadmin
    ports:
    - containerPort: 9000
    - containerPort: 9001
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: storage
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: api
    - port: 9001
      targetPort: 9001
      name: console
  selector:
    app: minio
