apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: logging
  labels:
    app: node-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
spec:
  clusterIP: None
  selector:
    app: node-exporter
  ports:
    - port: 9100
      targetPort: 9100
      name: metrics
