# MySQL 192.168.5.40:3306 — user root
apiVersion: v1
kind: Secret
metadata:
  name: mysql-exporter-dsn
  namespace: logging
type: Opaque
stringData:
  DATA_SOURCE_NAME: "root:pirago2018@tcp(192.168.5.40:3306)/"
