apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: logging
  labels:
    app: mysql-exporter
spec:
  selector:
    app: mysql-exporter
  ports:
    - port: 9104
      targetPort: 9104
      name: metrics
